# Generated by Django 4.1.3 on 2022-11-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, null=True, verbose_name='Category Name')),
                ('category_slug', models.CharField(max_length=50, null=True, unique=True, verbose_name='Category Slug')),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50, null=True, verbose_name='Product Item')),
                ('prod_slug', models.CharField(max_length=50, null=True, verbose_name='Product Slug')),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('prod_img', models.ImageField(null=True, upload_to='products/%d/%m/%Y', verbose_name='Product Image')),
                ('prod_latest', models.BooleanField(default=False, verbose_name='Latest Product')),
                ('prod_fresh', models.BooleanField(default=False, verbose_name='Fresh Product')),
                ('prod_available', models.BooleanField(default=True, verbose_name='Available Product')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['prod_name'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'prod_slug'], name='shop_produc_id_1f8c85_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['prod_name'], name='shop_produc_prod_na_5003b1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-date_created'], name='shop_produc_date_cr_869150_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_name'], name='shop_catego_categor_cb48d9_idx'),
        ),
    ]
