# Generated by Django 4.1.3 on 2022-11-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_prod_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(null=True, upload_to='category_icons', verbose_name='Category Image'),
        ),
    ]
