# Generated by Django 4.1.3 on 2022-11-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_category_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(error_messages='Enter your first name', help_text='First Name', max_length=30, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(error_messages='Enter your last name', help_text='Last name', max_length=30, null=True, verbose_name='Last Name')),
                ('email_user', models.EmailField(error_messages='Enter a valid email address', help_text='Email Address', max_length=254, verbose_name='Email')),
                ('text_desc', models.TextField(error_messages='Enter a text', help_text='Enter your text', null=True, verbose_name='Text')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
