# Generated by Django 4.1.3 on 2022-11-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_user', models.EmailField(error_messages='Enter a valid email address', help_text='Email Address', max_length=254, verbose_name='Email')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['email_user'],
            },
        ),
    ]
