# Generated by Django 4.1.3 on 2022-12-16 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50, null=True, verbose_name='Product Item')),
                ('prod_slug', models.CharField(max_length=50, null=True, verbose_name='Product Slug')),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('prod_img', models.ImageField(null=True, upload_to='search/%d/%m/%Y', verbose_name='Product Image')),
                ('prod_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Product Category')),
            ],
            options={
                'ordering': ['prod_name'],
            },
        ),
        migrations.AddIndex(
            model_name='searchproduct',
            index=models.Index(fields=['id', 'prod_slug'], name='shop_search_id_d95b90_idx'),
        ),
        migrations.AddIndex(
            model_name='searchproduct',
            index=models.Index(fields=['prod_name'], name='shop_search_prod_na_48a353_idx'),
        ),
    ]
