# Generated by Django 4.1.3 on 2022-11-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_category_category_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, null=True, verbose_name='Last Name')),
                ('email_user', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Home Address')),
                ('postal_code', models.CharField(max_length=30, null=True, verbose_name='Postal Code')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='City')),
                ('phone_num', models.CharField(max_length=30, null=True, verbose_name='Phone Number')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created'], name='order_order_created_708daa_idx'),
        ),
    ]
